### ISSUE TITLE
Unity 6000.03 API is out of date

### ISSUE THREAD

**Issue by QQ1273459693** [akidevcat/UnityPackage-AnalyticVolumetricLighting-Issues#7] opened 2024-06-05 11:00 UTC
![image](https://github.com/akidevcat/UnityPackage-AnalyticalVolumetricLighting-Public/assets/71361736/8a7abe7b-fd2a-41ed-b0fe-4a4faaf87836)
![image](https://github.com/akidevcat/UnityPackage-AnalyticalVolumetricLighting-Public/assets/71361736/3c8ec2ca-c42a-4e08-bb30-dbaae2d5e1a2)

**Comment by QQ1273459693** [comment] 2024-06-08 17:46
Heelo

**Comment by akidevcat** [comment] 2024-06-08 18:25
Thanks for reporting, I'll take a look for that in the 1.1 release this month

**Comment by liuyx23** [comment] 2024-06-11 02:44
will support rendergraph in Release1.1 ?

**Comment by liuyx23** [comment] 2024-06-13 06:41
> will support rendergraph in Release1.1 ?

HI，Need reply，please，   used in unity6

**Comment by akidevcat** [comment] 2024-06-13 10:35
> will support rendergraph in Release1.1 ?

I'll take a look. If that's a reasonable technical update in terms of the required code rewrite, then yes

**Comment by liuyx23** [comment] 2024-06-14 02:27
> > will support rendergraph in Release1.1 ?
> 
> I'll take a look. If that's a reasonable technical update in terms of the required code rewrite, then yes

As far as I know, Release 1.1 will be released this month. I hope it can be confirmed as soon as possible so that it can be updated in the Release milestones. thx

**Comment by akidevcat** [comment] 2024-06-27 20:20
Okay, Render Graph API seems to be a little bit more quirky, I'll be uploading a 1.1 update for pre-6 versions soon, and then making a rewrite for the new Render Graph API starting from Unity 6. As for now, you can use the Auto-upgrade feature in Unity, it should fix some obsolete stuff (basically just changing Area to Rectangle, and RenderTargetIdentifier to RTHandle). But yeah, that means turning on the compatibility mode. 

Rewrite might be done this weekend if I have enough time

**Comment by QQ1273459693** [comment] 2024-07-12 02:29
Is Unity6 already supported?

**Comment by battlecouchstudio** [comment] 2024-09-21 20:41
Replacing the deprecated names fixed the compiling issue but all the lights are now white point lights. Will wait for the official fix!

**Comment by buffman91** [comment] 2024-09-22 15:10
Unity 6 is not supported... When will it be available?

**Comment by akidevcat** [comment] 2024-10-13 02:40
Taking this for the next coming days with the in-depth code rewrite, should be done right before the Unity 6 LTS release

**Comment by akidevcat** [comment] 2024-10-18 09:01
Okay it takes a little bit more time to rewrite this portion of the code but I'm working on it, should be available in the coming days

**Comment by akidevcat** [comment] 2024-11-14 09:41
Update should be live now

**Closed as completed by akidevcat** 2024-11-14 09:41 UTC
Labels: bug
